# @package _global_
exp_name: ${masking.name}
seed: 0
model: wrn-22-2

wandb:
  project: cifar10
  name: ${dataset.name}_${exp_name}_density_${masking.density}

dataset:
  batch_size: 128
  validation_split: 0.1

masking:
  init_exp_name: Pruning-warmup

optimizer:
  epochs: 250
  training_multiplier: 1 #0.28 # 70 / 250
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  decay_frequency: 30000
  decay_factor: 0.2